projectdelphai/panorama-tab-groups

src/css/group.css, src/css/options.css, src/js/backup.js, src/js/drag.js, src/js/groupNodes.js, src/js/tabNodes.js, src/js/view.js, src/options.html, src/view.html
=> Separate pinned tabs

src/css/dark.css, src/css/options.css, src/css/view.css, src/icons/theme_dark.svg, src/icons/theme_light.svg, src/options.html
Using the default icon from the extension was misleading. Same icon but different action.
=> Changed toggle-theme icon

src/js/view.js
Currently this method saves only the current theme state from the toggle button. For future enhancement I'd like merge this toggle with the addon settings or for a far future read the theme colors from the browser.
=> Save theme toggle state in view setting

src/css/dark.css, src/css/group.css, src/css/view.css
Simplify some basic CSS without compromise autoplacement of groups and adjust dark theme.
=> Update CSS 

src/css/dark.css, src/css/view.css
2 small fixes and a little visibility change.
=> Adjust layout for pinned tabs

src/css/dark.css, src/css/options.css, src/css/view.css, src/icons/theme_dark.svg, src/icons/theme_light.svg, src/js/options.js, src/js/view.js, src/options.html, src/view.html
* resolve #46 by adding an option to position toolbar top/right/bottom/left
* move theme setting into options dialog
=> Enhance toolbar options

src/_locales/de/messages.json, src/_locales/en/messages.json, src/js/options.js, src/js/view/groupNodes.js, src/options.html
=> Add translations

src/js/background.js
When the user manually restores a window (e.g. by pressing Ctrl+Shift+N), the onCreated event will be called even if the window already contains group data. Add a check to make sure group data is not overwritten in these cases.
Fixes: https://github.com/projectdelphai/panorama-tab-groups/issues/55
=> Do not reset group data in restored windows

CONTRIBUTION.md, README.md, src/_locales/de/messages.json, src/_locales/en/messages.json, src/css/options.css, src/js/options.js, src/options.html
Add missing translations for options.
Refine some details.
#50
=> Add translations Pt. 2

src/_locales/zh_CN/messages.json, src/_locales/zh_TW/messages.json
Simplified and traditional translations are included. There might be a few mistakes I've missed, so if anyone notices please comment!
=> Add Chinese translations

CONTRIBUTION.md, src/_locales/de/messages.json, src/_locales/en/messages.json, src/_locales/fr_FR/messages.json, src/_locales/pl/messages.json, src/_locales/ru/messages.json, src/_locales/zh_CN/messages.json, src/_locales/zh_TW/messages.json, src/js/view/groupNodes.js, src/js/view/utils.js
=> Add plural rules and add Russian translation

src/js/background.js
It all boils down to 3 things I did in this PR:
- Replaced `var` with `let` because `var` can be evil
- Fixed missing async/await expressions. Not sure whether it will fix any of the existing bugs, but it bugged me.
- Made activate-next-group and activate-prev-group DRY
=> Refactor backgroundjs

src/_locales/es/messages.json, src/_locales/es_AR/messages.json
Adding the translation for my native language as others are adding translations since the last update. Also there is the plurals rule as indicated in the given resource.
Thanks for the project, I use it everyday as I have like 100+ opened always, you're feeding my bad habits. haha
=> Add Spanish translations

src/_locales/hu/messages.json
Hello! I really like this add-on.
=> Add Hungarian translation

src/js/background.js
If someone wants to check if this fix works to fix backups that'd be great. Else tomorrow evening (PST time), I'll do a quick run through to see if this change fixes the issue
=> Backup fix

src/_locales/en/messages.json, src/js/view/index.js
Hi! Absolutely love Panorama Tab Groups. Super productivity boost.
I was confused with what the two tiling buttons were for but figured it out today. I think it would be helpful to add tooltips so that is what I did.
=> Tooltips for tiling buttons

src/js/depends/dragscroll.js, src/js/view/groupNodes.js, src/view.html
I think being able to enable/disable infinite scrolling could be a very useful feature.
Actually, I have implemented only permanently enabled scrolling, with click/drag feature.
To test the new feature just grab a group to one of the window borders(right or bottom).
=> Infinite scrolling

src/js/background.js
=> Fix typo when setting badge background color

src/_locales/ru/messages.json
Added new rows and fixed a typo
=> Update russian translation

src/_locales/fr_FR/messages.json
Hello, I update the French translations :)
=> Add new popup mode French translation
